### ISSUE TITLE
feat: Implement `User` model, service and repository

### ISSUE THREAD

**Issue by apomalyn** [RoadTripMoustache/kana_to_kanji#135]
As a developer, I want to have a place to interact with the user data and functions

## Requirements

You can find the user definition [here](https://github.com/RoadTripMoustache/kana_to_kanji_api/issues/15)

Implement a repository that:
- retrieve the user from the local database (or shared preferences)
- keep in memory the current user 

## What needs to be done

- Use freezed (and Isar if user is stored in the database) to implement the `User`, and `UserPreferences` models
- Create a `UserDataLoader` class that:
  - synchronize the user with the API (depends on [API #16](https://github.com/RoadTripMoustache/kana_to_kanji_api/issues/16))  
- Create a `UserService` class that has the following function:
  - retrieve the user from the database or shared preferences
  - `Future<bool> updateUser(User updatedUser)` which update the locally stored user with a new one then synchronize with the API if necessary ((depends on [API #15](https://github.com/RoadTripMoustache/kana_to_kanji_api/issues/15)) 
  - placeholder functions (`throw  UnimplementedError()`) for:
    - `Future<bool> deleteUser(User user)`;
- Create an enum `AuthenticationMethod` with the values: `google`, `apple`, `classic`, `anonymous`
- Create a `UserRepository` class as a [listenable service](https://stacked.filledstacks.com/docs/in-depth/viewmodels#reactiveviewmodel), and add it to the locator. It should have the following methods:
  - getter for `User self` that returns the user connected  (registered as `listenToReactiveValues`)
  - `Future<bool> signOut()` which clear the current user
  - placeholder functions (`throw  UnimplementedError()`) for:
    - `Future<bool> signIn(AuthenticationMethod method, {bool isSilent = false, String? email, String? password})`
    - `Future<bool> register()`
    - `Future<bool> updateSelf(User updatedUser)`;
    - `Future<bool> linkAccount(AuthenticationMethod method, {String? email, String? password})`
    - `Future<bool> deleteUser()`;
    - `Future<bool> updatePassword(String oldPassword, String newPassword)`
- Update the locator to add the `UserRepository` and `UserDataLoader`

## Dependencies

Child of #130 

Depends on:

- API # 15 : https://github.com/RoadTripMoustache/kana_to_kanji_api/issues/15
- API # 16 : https://github.com/RoadTripMoustache/kana_to_kanji_api/issues/16

**Comment by Adaendra** [comment]
@apomalyn as seen [here](https://github.com/RoadTripMoustache/kana_to_kanji/issues/227), I won't process the knowledge level in this ticket.
