### ISSUE TITLE
fix: Align icons

### ISSUE THREAD

**Issue by apomalyn** [RoadTripMoustache/kana_to_kanji#209]
As a user, I want to see the same kind of icons everywhere

## Requirements

Update all the icons in the application to use the rounded design.

## What needs to be done

Go through the entire application and replace all `outlined` or classic icons with their `rounded` counterpart. Currently, only the `AppBottomNavigationBar` is allowed to have outlined icons.

Update the [icon list](https://nextcloud.candian.fr/index.php/f/1209159).

## Dependencies

Depends on:

- N/A

## Dev notes

- [Icons](https://nextcloud.candian.fr/index.php/f/1209159) used in the project
- [Material icons](https://fonts.google.com/icons?icon.platform=web&icon.set=Material+Icons&icon.style=Rounded) website

**Comment by Adaendra** [comment]
mdx file updated
