### ISSUE TITLE
feat: Add `groups` to `Kanji` and `Vocabulary`

### ISSUE THREAD

**Issue by apomalyn** [RoadTripMoustache/kana_to_kanji#220]
## Requirements

Add a `List<Group> groups` properties to `Kanji` and `Vocabulary`

## What needs to be done

Update the `Kanji` and `Vocabulary` models to have a `List<Group> groups` property. 
The JSON key should be `groups`.

## Dependencies

Depends on:

- https://github.com/RoadTripMoustache/kana_to_kanji_api/issues/70

**Comment by Adaendra** [comment]
As you can see on the following printscreens, it has been already done.

![image](https://github.com/RoadTripMoustache/kana_to_kanji/assets/36586573/acef7435-510c-4b8f-bb17-e6d88f9c963c)

![image](https://github.com/RoadTripMoustache/kana_to_kanji/assets/36586573/647b2473-6a8a-4b44-aaec-831c9190f61e)
