### ISSUE TITLE
Splash screen

### ISSUE THREAD

**Issue by apomalyn** [RoadTripMoustache/kana_to_kanji#25]
As a user, when the application is opening I don't want to see a simple white screen but something related to the application loading in the background.

This screen could also be used in the feature when downloading/updating the DB.

### Dev notes

If it's something animated, we could use: [Rive splash screen](https://pub.dev/packages/rive_splash_screen) otherwise the [native splash screen](https://pub.dev/packages/flutter_native_splash) should be enough

**Comment by apomalyn** [comment]
Splash screen proposition

| Light | Dark |
|-------|------|
| ![Screen Recording 2023-08-22 at 11 46 36 PM](https://github.com/RoadTripMoustache/kana_to_kanji/assets/22211097/c0874703-fb70-4a8f-8dec-f21840bfc3f3) | ![Screen Recording 2023-08-22 at 11 46 58 PM](https://github.com/RoadTripMoustache/kana_to_kanji/assets/22211097/bf82acc7-47f2-4ca7-816f-35f25efcf0d7) |

What do you think @Adaendra ? 😄

**Comment by Adaendra** [comment]
C'est vraiment cool! *o*
